Add QCArchive datastructures
choderalab/modelforge pull request #1
Opened 2023-08-01 15:35 UTC by wiederm

## Description
We want to provide a dataset structure for the most common datasets that are provided through the QCArchive infrastructure. These datasets should play nicely with the `pytorch` `dataloader` objects and inherit from `torch.utils.data.Dataset`.

## Todos
  - [x] Outline general structure 
  - [x] Implement QM9 toy dataset
 
## Questions
- [ ] How to best query different labels?
- [ ] Is there any use case for different datapoints beside coordinates?
- [ ] Is a `view` the best structure to perform queries on? 

## Status
- [ ] Ready to go

2023-08-02 18:01 UTC, chrisiacovella commented
I think, after a few minor changes, we should just merge this PR so we can create a separate one aimed at fixing the CI workflow.

2023-08-03 23:45 UTC, chrisiacovella requested changes
I think this is ready after:
1- remove qm9.py
2- remove the "to_file" call (as that is going to break things
3- see if the quick change to the test environment file fixes the failing CI

2023-08-04 10:29 UTC, wiederm commented on devtools/conda-envs/test_env.yaml
> +  - qcarchive
agreed, will change!

2023-08-04 10:33 UTC, wiederm commented on devtools/conda-envs/test_env.yaml
> +  - qcarchive
updated import

2023-08-04 10:40 UTC, wiederm commented on modelforge/dataset/dataset.py
> +        ) = self.dataset.get_molecules(), self.dataset.get_records(method="b3lyp")
agreed! modifyied the method accordinly.

2023-08-04 19:52 UTC, wiederm commented on modelforge/dataset/dataset.py
> +            dataset.set_view(dataset_file)  # NOTE: this doesn't work yet
oh, that is resolved now.

2023-08-04 20:03 UTC, wiederm commented on modelforge/dataset/qm9.py
thanks!

2023-08-04 21:38 UTC, chrisiacovella approved these changes
Looks good. Once merged, I'll get a PR going trying to resolve the CI issues.

2023-08-09 11:16 UTC, merged