Adding unit points to the public API
choderalab/modelforge pull request #56
Opened 2024-01-30 23:47 UTC by wiederm

## Description
Currently, we are not enforcing units at several public interfaces. This PR aims to fix this and enforces the internal use of the openmm unit system.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] Refactor all public APIs to ensure that we check and validate units
  - [ ] Conversion to openmm unit system

## Status
- [ ] Ready to go

2024-02-02 20:27 UTC, chrisiacovella commented
We had been using openff-units already in the package.  I don't think we should switch to openmm-units for the public facing API. Openff-units should be more flexible  (as we can easily convert to/from openmm units if we need) and has a convenient function unit.parse_expression, to make it easily to reassign units from the HDF5 files (which are encoded as strings).  

I think we should actually probably switch to openff-units in Chiron, just doing conversions from the openmm test systems (but that is a conversation for a different day in a different repo).

2024-02-02 20:28 UTC, chrisiacovella requested changes
as I just commented, I think we should be using openff-units. Maybe we can discuss this quickly offline.  I'm happy to switch these top openff.

2024-02-02 20:28 UTC, chrisiacovella commented on modelforge/tests/test_utils.py
> +    from openmm import unit
Why are you importing openmm units here? 

We had been using openff units in the rest of the code.  Openff-units are directly compatible with openmm units.  `openff.units.openmm` has  `to_openmm` and  `from_openmm` functions if we do need to convert.

2024-02-02 20:28 UTC, chrisiacovella commented on modelforge/tests/test_utils.py
> +    from openmm import unit
I think we should be using openff-units.

2024-02-02 20:28 UTC, chrisiacovella commented on modelforge/tests/test_utils.py
> +    assert gaussian_rbf.cutoff == cutoff.value_in_unit_system(unit.md_unit_system)
I think we should use openff units, as we've bee using those throughout the code already. 

we would use the syntax:

`assert gaussian_rbf.cutoff == cutoff.is_compatible_with(unit.nanometer)`

2024-02-02 22:34 UTC, chrisiacovella commented
After quick discussion, we are going to use openff-units.  I'll be grabbing a copy of the branch and making these changes.

2024-02-05 09:40 UTC, wiederm commented
Thanks @chrisiacovella for these changes!

Sorry for introducing yet another unit package! Thanks for catching that in time and making the necessary modifications!

2024-02-05 16:24 UTC, chrisiacovella approved these changes

2024-02-05 16:24 UTC, chrisiacovella commented on modelforge/potential/utils.py
> +class _CosineCutoff(nn.Module):
Should this be a public class

2024-02-05 16:28 UTC, merged